---
inherit_gem:
  rubocop-fnando: .rubocop-rails.yml

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 7.0
  NewCops: enable

Metrics:
  Enabled: false

Style/OpenStructUse:
  Exclude:
    - test/**/*.rb
