---
name: ruby-tests

on:
  pull_request_target:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Tests with Ruby ${{ matrix.ruby }}
    runs-on: "ubuntu-latest"
    if: |
      github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target' ||
      github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1"]

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        id: bundler-cache
        with:
          path: vendor/bundle
          key: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles('Gemfile.lock') }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install PostgreSQL client
        env:
          PGHOST: localhost
          PGUSER: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          psql -U postgres -c "create database test"

      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle update --jobs 4 --retry 3

      - name: Run Tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PGHOST: localhost
          PGUSER: postgres
          DATABASE_URL: postgres:///test
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          bundle exec rails test:all
          bundle exec rubocop
          bundle exec brakeman
