---
name: typescript-tests

on:
  pull_request_target:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Tests with Node ${{ matrix.node }}
    runs-on: "ubuntu-latest"
    if: |
      github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target' ||
      github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        node: ["16"]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: >
            ${{ runner.os }}-${{ matrix.node }}-yarn-${{
            hashFiles('**/yarn.lock') }}

      - name: Set up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Node version
        run: node -v

      - name: Install npm dependencies
        run: |
          yarn install

      - name: Run lint
        run: yarn lint

      - name: Run Tests
        run: yarn test:ci
